- hosts: localhost
  tasks:
    - name: Include ara report role
      include_role:
        name: ara-report
    - name: Include Zuul manifest role
      include_role:
        name: generate-zuul-manifest
    - name: Include upload logs role
      no_log: true
      include_role:
        name: upload-logs-swift
      vars:
        zuul_log_cloud_config: '{{ item }}'
        zuul_log_partition: true
        zuul_log_delete_after: 2592000
      with_random_choice:
        - '{{ opendev_cloud_fn_one }}'
        - '{{ opendev_cloud_rax_dfw }}'
        - '{{ opendev_cloud_rax_iad }}'
        - '{{ opendev_cloud_rax_ord }}'

- hosts: localhost
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - submit-logstash-jobs
    - submit-subunit-jobs
