- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_path_shard_build: true
    - log-inventory

- hosts: all
  pre_tasks:
    - name: Temporary fix for /root for virtualenv 20
      command: chmod o+rx /root
      become: yes
      tags:
        - skip_ansible_lint
      failed_when: false
    - name: Temporary fix for /root/local for virtualenv 20
      command: chmod -R o+rX /root/.local
      become: yes
      tags:
        - skip_ansible_lint
      failed_when: false
    # NOTE(pabelanger): Until we hit the validate-host role, we have a minimal
    # set of ansible variables collected by zuul-executor. This doesn't include
    # network variables (ansible_default_ipv4 / ansible_default_ipv6) so gather
    # these variables as they are important to the configure-unbound role.
    - name: Gather network facts
      setup:
        gather_subset: 'network'

  roles:
    - add-build-sshkey
    - start-zuul-console
    - ensure-output-dirs

- hosts: all
  roles:
    # NOTE(pabelanger): We run this role in its own play to ensure unbound is
    # restarted before proceeding with any other role. This is because we use
    # notify / handler to restart the unbound service. With ansible notify
    # actions are triggered at the end of each block of tasks in a play.
    - configure-unbound

- hosts: all
  roles:
    - validate-host
    - prepare-workspace-git
    - mirror-info
    - role: configure-mirrors
      set_apt_mirrors_trusted: True
  post_tasks:
    - name: Pin importlib-resources to 1.0.2 to fix Virtualenv and Tox
      become: yes
      shell: |
        if type -p pip3 ; then
          # Tox and virtualenv will be python3 installed on platforms with pip3
          pip3 install --upgrade importlib-resources==1.0.2
        else
          # Centos 7 shouldnt have python3 by default and need a pip2 install
          pip install --upgrade importlib-resources==1.0.2
        fi
      args:
        executable: /bin/bash
      # Do our best but if we fail don't cause job to fail as it may run
      # happily without virtualenv or tox.
      failed_when: false
