- hosts: all
  tasks:
    - name: get df disk usage
      raw: df

    - name: get df inode usage
      raw: df -i

    - name: get l2 networking
      raw: ip link

    - name: get l3 networking
      raw: ip addr
