- hosts: localhost
  tasks:
    - name: Include Zuul manifest role
      include_role:
        name: generate-zuul-manifest
    - name: Include upload logs role
      no_log: true
      include_role:
        name: test-upload-logs-swift
      vars:
        zuul_log_path_shard_build: true
        zuul_log_cloud_config: '{{ item }}'
        zuul_log_partition: true
        zuul_log_delete_after: 2592000
        # Unique log prefix to avoid container name collisions when ceph is
        # used.
        zuul_log_container: zuul_opendev_logs
      with_random_choice:
        - '{{ opendev_cloud_fn_one }}'
        - '{{ opendev_cloud_ovh_bhs1 }}'
        - '{{ opendev_cloud_ovh_gra1 }}'
        - '{{ opendev_cloud_rax_dfw }}'
        - '{{ opendev_cloud_rax_iad }}'
        - '{{ opendev_cloud_rax_ord }}'

- hosts: localhost
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - submit-logstash-jobs
    - submit-subunit-jobs
