- hosts: localhost
  roles:
    - role: ara-report
    - role: upload-logs-swift
      zuul_log_cloud_config: '{{ log_cloud_config }}'
      zuul_log_partition: true

- hosts: localhost
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - submit-logstash-jobs
    - submit-subunit-jobs
