- hosts: localhost
  tasks:
    - name: Include ara report role
      include_role:
        name: ara-report
    - name: Include Zuul manifest role
      include_role:
        name: generate-zuul-manifest
    - name: Include upload logs role
      include_role:
        name: upload-logs-swift
      vars:
        zuul_log_cloud_config: '{{ item }}'
        zuul_log_partition: true
      with_random_choice:
        - '{{ opendev_rax_dfw }}'
        - '{{ opendev_rax_ord }}'
        - '{{ opendev_rax_iad }}'

- hosts: localhost
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - submit-logstash-jobs
    - submit-subunit-jobs
